"""
Django settings for meuprojeto project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from django.core.exceptions import ImproperlyConfigured
from pathlib import Path
import os # ou from pathlib import Path se já estiver usando Path
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) 
# Ou a versão com Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable not set")

# SECURITY WARNING: don't run with debug turned on in production!
import os
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',')
if not DEBUG and not ALLOWED_HOSTS:
    raise ValueError("ALLOWED_HOSTS must not be empty when DEBUG is False.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'contas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meuprojeto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meuprojeto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Adicione esta configuração: Lista de diretórios onde o Django procurará
# por arquivos estáticos adicionais, além dos diretórios 'static' dos apps.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Aponta para uma pasta 'static' na raiz do projeto
]

# --- ADICIONE ESTA LINHA ---
# Diretório onde o collectstatic irá juntar todos os arquivos estáticos para produção
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_production') 

# --- ADICIONE AS CONFIGURAÇÕES DE MÍDIA ABAIXO ---
# URL base para servir os arquivos de mídia enviados pelos usuários
MEDIA_URL = '/media/'

# Caminho no sistema de arquivos onde os arquivos de mídia serão armazenados
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# --- FIM DAS NOVAS CONFIGURAÇÕES DE MÍDIA ---

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Para onde redirecionar após o login bem-sucedido
LOGIN_REDIRECT_URL = '/' # Redireciona para a página inicial

# Para onde redirecionar após o logout
LOGOUT_REDIRECT_URL = '/' # Redireciona para a página inicial

LOGIN_URL = '/contas/login/'

# Configuração de Email para Desenvolvimento (envia para o console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'naoresponda@sua-plataforma.com' # Um email padrão

# ATENÇÃO: Para produção, use variáveis de ambiente!
# Exemplo com python-dotenv:
# import os
# from dotenv import load_dotenv
# load_dotenv() # Carrega .env
