# Generated by Django 5.2 on 2025-05-03 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('endereco', models.TextField(blank=True)),
                ('contato_emergencia', models.CharField(blank=True, help_text='Nome e telefone do contato de emergência', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_profissional', models.CharField(choices=[('PSICOLOGO', 'Psicólogo(a)'), ('PSIQUIATRA', 'Psiquiatra')], max_length=15)),
                ('numero_registro', models.CharField(help_text='Número do CRP ou CRM', max_length=20, unique=True)),
                ('especialidades', models.CharField(blank=True, help_text='Separado por vírgulas, ex: TCC, Psicanálise', max_length=255)),
                ('bio', models.TextField(blank=True, help_text='Breve descrição sobre sua abordagem, experiência, etc.')),
                ('telefone_contato', models.CharField(blank=True, max_length=20)),
                ('endereco_consultorio', models.TextField(blank=True)),
                ('anos_experiencia', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profissional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
