# Generated by Django 5.2 on 2025-05-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprofissional',
            name='numero_registro',
            field=models.CharField(blank=True, help_text='Número do CRP ou CRM', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='perfilprofissional',
            name='tipo_profissional',
            field=models.CharField(blank=True, choices=[('PSICOLOGO', 'Psicólogo(a)'), ('PSIQUIATRA', 'Psiquiatra')], max_length=15, null=True),
        ),
    ]
