# Generated by Django 5.2 on 2025-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_perfilprofissional_numero_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='perfilprofissional',
            name='especialidades',
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='contas.especialidade'),
        ),
    ]
