# Generated by Django 5.2 on 2025-05-08 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_disponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Início do Bloqueio')),
                ('data_fim', models.DateTimeField(verbose_name='Fim do Bloqueio')),
                ('motivo', models.CharField(blank=True, help_text='Opcional: ex: Férias, Conferência', max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios', to='contas.perfilprofissional')),
            ],
            options={
                'verbose_name': 'Bloqueio de Tempo',
                'verbose_name_plural': 'Bloqueios de Tempo',
                'ordering': ['profissional', 'data_inicio'],
            },
        ),
    ]
