# Generated by Django 5.2 on 2025-05-08 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_bloqueiotempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadeAvulsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Início do Horário Avulso')),
                ('data_hora_fim', models.DateTimeField(verbose_name='Fim do Horário Avulso')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_avulsas', to='contas.perfilprofissional')),
            ],
            options={
                'verbose_name': 'Disponibilidade Avulsa',
                'verbose_name_plural': 'Disponibilidades Avulsas',
                'ordering': ['profissional', 'data_hora_inicio'],
            },
        ),
    ]
