# Generated by Django 5.2 on 2025-05-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_disponibilidadeavulsa'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regra', models.CharField(choices=[('SEMANAL', 'Semanal Recorrente'), ('ESPECIFICA', 'Data/Hora Específica')], max_length=10, verbose_name='Tipo de Regra')),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Dia da Semana (para Semanal)')),
                ('hora_inicio_recorrente', models.TimeField(blank=True, null=True, verbose_name='Hora Início (para Semanal)')),
                ('hora_fim_recorrente', models.TimeField(blank=True, null=True, verbose_name='Hora Fim (para Semanal)')),
                ('data_hora_inicio_especifica', models.DateTimeField(blank=True, null=True, verbose_name='Início Específico (Data e Hora)')),
                ('data_hora_fim_especifica', models.DateTimeField(blank=True, null=True, verbose_name='Fim Específico (Data e Hora)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_disponibilidade', to='contas.perfilprofissional')),
            ],
            options={
                'verbose_name': 'Regra de Disponibilidade',
                'verbose_name_plural': 'Regras de Disponibilidade',
                'ordering': ['profissional', 'tipo_regra', 'dia_semana', 'data_hora_inicio_especifica', 'hora_inicio_recorrente'],
            },
        ),
    ]
