# Generated by Django 5.2 on 2025-05-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_regradisponibilidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disponibilidadeavulsa',
            name='profissional',
        ),
        migrations.AlterModelOptions(
            name='especialidade',
            options={'ordering': ['nome'], 'verbose_name': 'Especialidade', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='perfilpaciente',
            options={'verbose_name': 'Perfil Paciente', 'verbose_name_plural': 'Perfis Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='perfilprofissional',
            options={'verbose_name': 'Perfil Profissional', 'verbose_name_plural': 'Perfis Profissionais'},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='notas_paciente',
            field=models.TextField(blank=True, help_text='Obs. paciente', null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='notas_profissional',
            field=models.TextField(blank=True, help_text='Obs. profissional', null=True),
        ),
        migrations.AlterField(
            model_name='regradisponibilidade',
            name='dia_semana',
            field=models.IntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], null=True, verbose_name='Dia da Semana (p/ Semanal)'),
        ),
        migrations.AlterField(
            model_name='regradisponibilidade',
            name='hora_fim_recorrente',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Fim (p/ Semanal)'),
        ),
        migrations.AlterField(
            model_name='regradisponibilidade',
            name='hora_inicio_recorrente',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Início (p/ Semanal)'),
        ),
        migrations.DeleteModel(
            name='Disponibilidade',
        ),
        migrations.DeleteModel(
            name='DisponibilidadeAvulsa',
        ),
    ]
