# Generated by Django 5.2 on 2025-05-10 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_remove_disponibilidadeavulsa_profissional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_como_paciente', to='contas.perfilpaciente'),
        ),
    ]
