# Generated by Django 5.2 on 2025-05-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_delete_bloqueiotempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='url_videochamada',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Videochamada'),
        ),
    ]
