# Generated by Django 5.2 on 2025-06-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_agendamento_url_videochamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='pagamento_id',
            field=models.CharField(blank=True, help_text='ID da transação no gateway de pagamento (ex: Stripe Payment Intent ID)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('FALHOU', 'Falhou'), ('REEMBOLSADO', 'Reembolsado')], default='PENDENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor da consulta em R$. Deixe em branco se for gratuito ou a combinar.', max_digits=7, null=True),
        ),
    ]
