# Generated by Django 5.2 on 2025-06-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_agendamento_pagamento_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/pacientes/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='perfilprofissional',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/profissionais/', verbose_name='Foto de Perfil'),
        ),
    ]
